-- Reset Database and Table Structure
-- WARNING: This will delete all data!

TRUNCATE TABLE luvvies_crush_scores;

-- Ensure table structure is correct (idempotent)
CREATE TABLE IF NOT EXISTS luvvies_crush_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    player_name TEXT NOT NULL,
    score INTEGER NOT NULL,
    level INTEGER NOT NULL,
    difficulty TEXT NOT NULL,
    version TEXT,
    user_id UUID -- Optional: for tracking unique users if needed
);

-- Index for faster leaderboard lookups
CREATE INDEX IF NOT EXISTS idx_scores_difficulty_score ON luvvies_crush_scores (difficulty, score DESC);
