-- Supabase Setup for Luvvies Crush Leaderboard

 -- 1. Create Table (if not exists)
 create table if not exists public.luvvies_crush_scores (
   id bigint generated by default as identity primary key,
   created_at timestamp with time zone default timezone('utc'::text, now()) not null,
   player_name text not null,
   score bigint not null,
   level integer not null,
   difficulty text not null,
   version text,
   user_id text -- UUID from cookie
 );

 -- 2. Enable RLS
 alter table public.luvvies_crush_scores enable row level security;

 -- 3. Policies
 -- Allow anyone to read (for leaderboard display)
 create policy "Public profiles are viewable by everyone."
   on public.luvvies_crush_scores for select
   using ( true );

 -- Allow anyone to insert (posting scores)
 create policy "Anyone can upload a score."
   on public.luvvies_crush_scores for insert
   with check ( true );

 -- 4. Unique Constraint to prevent spamming
 -- One score per user per difficulty? Or per level?
 -- User request: "so user cannot post multiple times".
 -- A reasonable constraint is unique(user_id, score, level, difficulty) to prevent exact duplicates.
 -- Or unique(user_id, difficulty) if we only want 1 highscore per difficulty per user.
 -- Let's assume we want to prevent duplicate submissions of the *same* game result.
 -- Or better: Only keep the highest score for a user?
 -- Since we do filtering on client side currently, the DB can allow multiple.
 -- But to strictly prevent "spam", we can rate limit or use a unique index.
 -- Let's add a unique index on (user_id, score, level, difficulty) to stop exact re-posts.

 create unique index if not exists idx_unique_score_submission
   on public.luvvies_crush_scores (user_id, score, level, difficulty);
